/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CdnGetPurgeStatusResponse The response from a request to retrieve the status of a purge request
type CdnGetPurgeStatusResponse struct {
	// The purge request's progress, ranging from 0.0 to 1.0
	Progress float32 `json:"progress,omitempty"`
}
