/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// OriginPullPolicyDefaultCacheBehaviorEnumWrapperValue the model 'OriginPullPolicyDefaultCacheBehaviorEnumWrapperValue'
type OriginPullPolicyDefaultCacheBehaviorEnumWrapperValue string

// List of OriginPullPolicyDefaultCacheBehaviorEnumWrapperValue
const (
	ORIGINPULLPOLICYDEFAULTCACHEBEHAVIORENUMWRAPPERVALUE_UNKNOWN OriginPullPolicyDefaultCacheBehaviorEnumWrapperValue = "UNKNOWN"
	ORIGINPULLPOLICYDEFAULTCACHEBEHAVIORENUMWRAPPERVALUE_BYPASS OriginPullPolicyDefaultCacheBehaviorEnumWrapperValue = "bypass"
	ORIGINPULLPOLICYDEFAULTCACHEBEHAVIORENUMWRAPPERVALUE_TTL OriginPullPolicyDefaultCacheBehaviorEnumWrapperValue = "ttl"
)
