/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CdnCreateSiteRequestFeature The features available to the new CDN site  Multiple products can served on a single CDN site. Features control how those products are managed on the StackPath backend.   - CDN: The site will have CDN caching abilities  - WAF: The site is protected by the StackPath Web Application Firewall
type CdnCreateSiteRequestFeature string

// List of cdnCreateSiteRequestFeature
const (
	CDN CdnCreateSiteRequestFeature = "CDN"
	WAF CdnCreateSiteRequestFeature = "WAF"
)
