/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
import (
	"time"
)
// CdnSiteScript A serverless script  Serverless scripts are hosted and executed on StackPath's edge nodes.
type CdnSiteScript struct {
	// A serverless script's unique identifier
	Id string `json:"id,omitempty"`
	// The ID of the stack to which a serverless script's site belongs
	StackId string `json:"stackId,omitempty"`
	// The ID of the site to which a serverless script belongs
	SiteId string `json:"siteId,omitempty"`
	// A serverless script's name
	Name string `json:"name,omitempty"`
	// A serverless script's version number  Version numbers start at 1 and are incremented every time the script is updated.
	Version string `json:"version,omitempty"`
	// Base64 encoded contents of a serverless script
	Code string `json:"code,omitempty"`
	// The URL paths that incoming requests should answer with a serverless script  Every serverless script needs at least one path, and paths must be unique.
	Paths []string `json:"paths,omitempty"`
	// The date a serverless script was created
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// The date a serverless script was last updated
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
}
