/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// BandwidthRateLimitSustainedRateUnitsEnumWrapperValue the model 'BandwidthRateLimitSustainedRateUnitsEnumWrapperValue'
type BandwidthRateLimitSustainedRateUnitsEnumWrapperValue string

// List of BandwidthRateLimitSustainedRateUnitsEnumWrapperValue
const (
	BANDWIDTHRATELIMITSUSTAINEDRATEUNITSENUMWRAPPERVALUE_UNKNOWN BandwidthRateLimitSustainedRateUnitsEnumWrapperValue = "UNKNOWN"
	BANDWIDTHRATELIMITSUSTAINEDRATEUNITSENUMWRAPPERVALUE_KILOBIT BandwidthRateLimitSustainedRateUnitsEnumWrapperValue = "kilobit"
	BANDWIDTHRATELIMITSUSTAINEDRATEUNITSENUMWRAPPERVALUE_KILOBYTE BandwidthRateLimitSustainedRateUnitsEnumWrapperValue = "kilobyte"
)
