/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CustconfOriginPullProtocolProtocolEnumWrapperValue the model 'CustconfOriginPullProtocolProtocolEnumWrapperValue'
type CustconfOriginPullProtocolProtocolEnumWrapperValue string

// List of custconfOriginPullProtocolProtocolEnumWrapperValue
const (
	UNKNOWN CustconfOriginPullProtocolProtocolEnumWrapperValue = "UNKNOWN"
	HTTP CustconfOriginPullProtocolProtocolEnumWrapperValue = "http"
	HTTPS CustconfOriginPullProtocolProtocolEnumWrapperValue = "https"
	MATCH CustconfOriginPullProtocolProtocolEnumWrapperValue = "match"
)
