/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn

import (
	"encoding/json"
)

// CdnCreateScopeRequest struct for CdnCreateScopeRequest
type CdnCreateScopeRequest struct {
	// The HTTP request path the scope should respond to
	Path *string `json:"path,omitempty"`
	// The StackPath billing platform to create the scope on
	Platform *string `json:"platform,omitempty"`
}

// NewCdnCreateScopeRequest instantiates a new CdnCreateScopeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnCreateScopeRequest() *CdnCreateScopeRequest {
	this := CdnCreateScopeRequest{}
	return &this
}

// NewCdnCreateScopeRequestWithDefaults instantiates a new CdnCreateScopeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnCreateScopeRequestWithDefaults() *CdnCreateScopeRequest {
	this := CdnCreateScopeRequest{}
	return &this
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *CdnCreateScopeRequest) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCreateScopeRequest) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *CdnCreateScopeRequest) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *CdnCreateScopeRequest) SetPath(v string) {
	o.Path = &v
}

// GetPlatform returns the Platform field value if set, zero value otherwise.
func (o *CdnCreateScopeRequest) GetPlatform() string {
	if o == nil || o.Platform == nil {
		var ret string
		return ret
	}
	return *o.Platform
}

// GetPlatformOk returns a tuple with the Platform field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnCreateScopeRequest) GetPlatformOk() (*string, bool) {
	if o == nil || o.Platform == nil {
		return nil, false
	}
	return o.Platform, true
}

// HasPlatform returns a boolean if a field has been set.
func (o *CdnCreateScopeRequest) HasPlatform() bool {
	if o != nil && o.Platform != nil {
		return true
	}

	return false
}

// SetPlatform gets a reference to the given string and assigns it to the Platform field.
func (o *CdnCreateScopeRequest) SetPlatform(v string) {
	o.Platform = &v
}

func (o CdnCreateScopeRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.Platform != nil {
		toSerialize["platform"] = o.Platform
	}
	return json.Marshal(toSerialize)
}

type NullableCdnCreateScopeRequest struct {
	value *CdnCreateScopeRequest
	isSet bool
}

func (v NullableCdnCreateScopeRequest) Get() *CdnCreateScopeRequest {
	return v.value
}

func (v *NullableCdnCreateScopeRequest) Set(val *CdnCreateScopeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnCreateScopeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnCreateScopeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnCreateScopeRequest(val *CdnCreateScopeRequest) *NullableCdnCreateScopeRequest {
	return &NullableCdnCreateScopeRequest{value: val, isSet: true}
}

func (v NullableCdnCreateScopeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnCreateScopeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
