/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CdnUpdateScopeRuleConfigurationRequest struct for CdnUpdateScopeRuleConfigurationRequest
type CdnUpdateScopeRuleConfigurationRequest struct {
	Configuration CustconfConfiguration `json:"configuration,omitempty"`
}
