/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn

import (
	"encoding/json"
)

// CustconfHttp2Support Enable support of HTTP2
type CustconfHttp2Support struct {
	// This is used by the API to perform conflict checking
	Id *string `json:"id,omitempty"`
	// Enable support of HTTP2
	Enabled *bool `json:"enabled,omitempty"`
}

// NewCustconfHttp2Support instantiates a new CustconfHttp2Support object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustconfHttp2Support() *CustconfHttp2Support {
	this := CustconfHttp2Support{}
	return &this
}

// NewCustconfHttp2SupportWithDefaults instantiates a new CustconfHttp2Support object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustconfHttp2SupportWithDefaults() *CustconfHttp2Support {
	this := CustconfHttp2Support{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *CustconfHttp2Support) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustconfHttp2Support) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *CustconfHttp2Support) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *CustconfHttp2Support) SetId(v string) {
	o.Id = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *CustconfHttp2Support) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CustconfHttp2Support) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *CustconfHttp2Support) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *CustconfHttp2Support) SetEnabled(v bool) {
	o.Enabled = &v
}

func (o CustconfHttp2Support) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	return json.Marshal(toSerialize)
}

type NullableCustconfHttp2Support struct {
	value *CustconfHttp2Support
	isSet bool
}

func (v NullableCustconfHttp2Support) Get() *CustconfHttp2Support {
	return v.value
}

func (v *NullableCustconfHttp2Support) Set(val *CustconfHttp2Support) {
	v.value = val
	v.isSet = true
}

func (v NullableCustconfHttp2Support) IsSet() bool {
	return v.isSet
}

func (v *NullableCustconfHttp2Support) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustconfHttp2Support(val *CustconfHttp2Support) *NullableCustconfHttp2Support {
	return &NullableCustconfHttp2Support{value: val, isSet: true}
}

func (v NullableCustconfHttp2Support) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustconfHttp2Support) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
