/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CustconfCustomHeader The X-Forwarded-For header policy allows you to override the name of the X-Forwarded-For header the CDN sends to your origin.
type CustconfCustomHeader struct {
	// This is used by the API to perform conflict checking
	Id string `json:"id,omitempty"`
	// This is the name of the X-Forwarded-For header you want the CDN to use when making requests to your basic authorization server.
	XForwardedForAuth string `json:"xForwardedForAuth,omitempty"`
	// This is the name of the X-Forwarded-For header you want the CDN to use when making requests to your origin server.
	XForwardedForOrigin string `json:"xForwardedForOrigin,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
}
