/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn

import (
	"encoding/json"
)

// CdnCertificateVerificationMethod The Certificate Verification Method  Verification method used to validate a requested certificate on a site   - DNS: Verify a certificate using DNS records  - HTTP: Verify a certificate by using HTTP validation. This will require all hosts in the certificate point to the site's stackpathcdn.com delivery domain or IP address
type CdnCertificateVerificationMethod string

// List of cdnCertificateVerificationMethod
const (
	DNS CdnCertificateVerificationMethod = "DNS"
	HTTP CdnCertificateVerificationMethod = "HTTP"
)

// Ptr returns reference to cdnCertificateVerificationMethod value
func (v CdnCertificateVerificationMethod) Ptr() *CdnCertificateVerificationMethod {
	return &v
}


type NullableCdnCertificateVerificationMethod struct {
	value *CdnCertificateVerificationMethod
	isSet bool
}

func (v NullableCdnCertificateVerificationMethod) Get() *CdnCertificateVerificationMethod {
	return v.value
}

func (v *NullableCdnCertificateVerificationMethod) Set(val *CdnCertificateVerificationMethod) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnCertificateVerificationMethod) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnCertificateVerificationMethod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnCertificateVerificationMethod(val *CdnCertificateVerificationMethod) *NullableCdnCertificateVerificationMethod {
	return &NullableCdnCertificateVerificationMethod{value: val, isSet: true}
}

func (v NullableCdnCertificateVerificationMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnCertificateVerificationMethod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
