/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CdnScope A CDN site scope  Scopes hold a CDN site's configuration. Every site has at least one \"root\" scope that handles primary configuration.
type CdnScope struct {
	// A CDN site scope's unique identifier
	Id string `json:"id,omitempty"`
	// A CDN site scope's platform  Scope platforms are used internally by StackPath for metrics collection and billing purposes. Typically, most site scope platforms have the value \"CDS\".
	Platform string `json:"platform,omitempty"`
	// The HTTP request path that is handled by a scope
	Path string `json:"path,omitempty"`
}
