/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn

import (
	"encoding/json"
)

// CdnGetCertificateResponse The response from a request to retrieve an individual SSL certificate on a stack
type CdnGetCertificateResponse struct {
	Certificate *CdnCertificate `json:"certificate,omitempty"`
}

// NewCdnGetCertificateResponse instantiates a new CdnGetCertificateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCdnGetCertificateResponse() *CdnGetCertificateResponse {
	this := CdnGetCertificateResponse{}
	return &this
}

// NewCdnGetCertificateResponseWithDefaults instantiates a new CdnGetCertificateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCdnGetCertificateResponseWithDefaults() *CdnGetCertificateResponse {
	this := CdnGetCertificateResponse{}
	return &this
}

// GetCertificate returns the Certificate field value if set, zero value otherwise.
func (o *CdnGetCertificateResponse) GetCertificate() CdnCertificate {
	if o == nil || o.Certificate == nil {
		var ret CdnCertificate
		return ret
	}
	return *o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CdnGetCertificateResponse) GetCertificateOk() (*CdnCertificate, bool) {
	if o == nil || o.Certificate == nil {
		return nil, false
	}
	return o.Certificate, true
}

// HasCertificate returns a boolean if a field has been set.
func (o *CdnGetCertificateResponse) HasCertificate() bool {
	if o != nil && o.Certificate != nil {
		return true
	}

	return false
}

// SetCertificate gets a reference to the given CdnCertificate and assigns it to the Certificate field.
func (o *CdnGetCertificateResponse) SetCertificate(v CdnCertificate) {
	o.Certificate = &v
}

func (o CdnGetCertificateResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Certificate != nil {
		toSerialize["certificate"] = o.Certificate
	}
	return json.Marshal(toSerialize)
}

type NullableCdnGetCertificateResponse struct {
	value *CdnGetCertificateResponse
	isSet bool
}

func (v NullableCdnGetCertificateResponse) Get() *CdnGetCertificateResponse {
	return v.value
}

func (v *NullableCdnGetCertificateResponse) Set(val *CdnGetCertificateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCdnGetCertificateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCdnGetCertificateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCdnGetCertificateResponse(val *CdnGetCertificateResponse) *NullableCdnGetCertificateResponse {
	return &NullableCdnGetCertificateResponse{value: val, isSet: true}
}

func (v NullableCdnGetCertificateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCdnGetCertificateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
