/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CdnSiteFeature The features available to CDN sites  Multiple products can be served on a single CDN site. Features control how those products are managed on the StackPath backend.   - UNKNOWN: StackPath is unable to determine a site's feature  - CDN: A site has CDN caching abilities  - WAF: A site is protected by the StackPath Web Application Firewall
type CdnSiteFeature string

// List of cdnSiteFeature
const (
	UNKNOWN CdnSiteFeature = "UNKNOWN"
	CDN CdnSiteFeature = "CDN"
	WAF CdnSiteFeature = "WAF"
)
