/*
 * Content Delivery Network
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cdn
// CdnUpdateSiteScriptResponse The response from a request to update an EdgeEngine script
type CdnUpdateSiteScriptResponse struct {
	Script CdnSiteScript `json:"script,omitempty"`
}
