/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites
// DeliveryCreateSiteDeliveryDomainResponse The response from a request to add a hostname to a CDN site scope
type DeliveryCreateSiteDeliveryDomainResponse struct {
	Domain SchemadeliveryDeliveryDomain `json:"domain,omitempty"`
}
