/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites
// DeliveryUpdateOriginRequest struct for DeliveryUpdateOriginRequest
type DeliveryUpdateOriginRequest struct {
	Http DeliveryHttpOrigin `json:"http,omitempty"`
	StackpathStorage DeliveryStackPathStorageOrigin `json:"stackpathStorage,omitempty"`
	S3Storage DeliveryAwss3Origin `json:"s3Storage,omitempty"`
	GoogleCloudStorage DeliveryGoogleStorageOrigin `json:"googleCloudStorage,omitempty"`
}
