/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites

import (
	"encoding/json"
)

// DeliveryGetSitesResponse The response from a request to retrieve a stack's sites
type DeliveryGetSitesResponse struct {
	PageInfo *PaginationPageInfo `json:"pageInfo,omitempty"`
	// The requested sites
	Results *[]DeliverySite `json:"results,omitempty"`
}

// NewDeliveryGetSitesResponse instantiates a new DeliveryGetSitesResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeliveryGetSitesResponse() *DeliveryGetSitesResponse {
	this := DeliveryGetSitesResponse{}
	return &this
}

// NewDeliveryGetSitesResponseWithDefaults instantiates a new DeliveryGetSitesResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeliveryGetSitesResponseWithDefaults() *DeliveryGetSitesResponse {
	this := DeliveryGetSitesResponse{}
	return &this
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *DeliveryGetSitesResponse) GetPageInfo() PaginationPageInfo {
	if o == nil || o.PageInfo == nil {
		var ret PaginationPageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryGetSitesResponse) GetPageInfoOk() (*PaginationPageInfo, bool) {
	if o == nil || o.PageInfo == nil {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *DeliveryGetSitesResponse) HasPageInfo() bool {
	if o != nil && o.PageInfo != nil {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given PaginationPageInfo and assigns it to the PageInfo field.
func (o *DeliveryGetSitesResponse) SetPageInfo(v PaginationPageInfo) {
	o.PageInfo = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *DeliveryGetSitesResponse) GetResults() []DeliverySite {
	if o == nil || o.Results == nil {
		var ret []DeliverySite
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DeliveryGetSitesResponse) GetResultsOk() (*[]DeliverySite, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *DeliveryGetSitesResponse) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []DeliverySite and assigns it to the Results field.
func (o *DeliveryGetSitesResponse) SetResults(v []DeliverySite) {
	o.Results = &v
}

func (o DeliveryGetSitesResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PageInfo != nil {
		toSerialize["pageInfo"] = o.PageInfo
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableDeliveryGetSitesResponse struct {
	value *DeliveryGetSitesResponse
	isSet bool
}

func (v NullableDeliveryGetSitesResponse) Get() *DeliveryGetSitesResponse {
	return v.value
}

func (v *NullableDeliveryGetSitesResponse) Set(val *DeliveryGetSitesResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeliveryGetSitesResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeliveryGetSitesResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeliveryGetSitesResponse(val *DeliveryGetSitesResponse) *NullableDeliveryGetSitesResponse {
	return &NullableDeliveryGetSitesResponse{value: val, isSet: true}
}

func (v NullableDeliveryGetSitesResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeliveryGetSitesResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
