/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites
// CustconfFlvPseudoStreaming struct for CustconfFlvPseudoStreaming
type CustconfFlvPseudoStreaming struct {
	// This is used by the API to perform conflict checking
	Id string `json:"id,omitempty"`
	JumpToByteInitialBytesParam string `json:"jumpToByteInitialBytesParam,omitempty"`
	JumpToByteStartOffsetParam string `json:"jumpToByteStartOffsetParam,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
}
