/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites
// CustconfCustomer struct for CustconfCustomer
type CustconfCustomer struct {
	// This is used by the API to perform conflict checking
	Id string `json:"id,omitempty"`
	// String of values delimited by a ',' character.
	AccessLogFields string `json:"accessLogFields,omitempty"`
	// String of values delimited by a ',' character.
	OpLogFields string `json:"opLogFields,omitempty"`
	// String of values delimited by a ',' character.
	ReceiptLogFields string `json:"receiptLogFields,omitempty"`
}
