/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites
// BandwidthRateLimitSustainedRateUnitsEnumWrapperValue the model 'BandwidthRateLimitSustainedRateUnitsEnumWrapperValue'
type BandwidthRateLimitSustainedRateUnitsEnumWrapperValue string

// List of BandwidthRateLimitSustainedRateUnitsEnumWrapperValue
const (
	UNKNOWN BandwidthRateLimitSustainedRateUnitsEnumWrapperValue = "UNKNOWN"
	KILOBIT BandwidthRateLimitSustainedRateUnitsEnumWrapperValue = "kilobit"
	KILOBYTE BandwidthRateLimitSustainedRateUnitsEnumWrapperValue = "kilobyte"
)
