/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites
// DeliveryGetOriginResponse The response with the requested origin
type DeliveryGetOriginResponse struct {
	Origin SchemadeliveryOrigin `json:"origin,omitempty"`
}
