/*
 * Sites
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package sites
// CustconfAuthUrlSign URL Signing policies allow you to restrict access to your content by configuring a \"shared secret\" with StackPath. This \"shared secret\" is used to apply an MD5 hashing algorithm on the URL to validate the signature supplied on the request. Since the \"shared secret\" is only known by the publisher and StackPath, URL signatures cannot be generated by unauthorized users.
type CustconfAuthUrlSign struct {
	// This is used by the API to perform conflict checking
	Id string `json:"id,omitempty"`
	// This is the name of the query string parameter that will be used by the publisher to specify the signature for the URL.
	TokenField string `json:"tokenField,omitempty"`
	// Select this option if you want StackPath to exclude query string parameters specified after the passphrase in the validation process.
	IgnoreFieldsAfterToken bool `json:"ignoreFieldsAfterToken,omitempty"`
	// This is the name of the query string parameter that contains the value of the secret. This query string parameter is only used during the generation and validation of a URL signature and should not be present in the published URL.
	PassPhraseField string `json:"passPhraseField,omitempty"`
	// The shared secret used during the signing process. This value should only be known by StackPath and systems authorized to sign your content.
	PassPhrase string `json:"passPhrase,omitempty"`
	// This is the name of the query string parameter that contains the Epoch time after which the URL is considered invalid.
	ExpiresField string `json:"expiresField,omitempty"`
	// This is a query string parameter that contains an IPv4 address to which the published URL will be restricted.
	IpAddressField string `json:"ipAddressField,omitempty"`
	// This is a query string parameter used to limit the number of characters in the path that should be considered when validating the URL signature. This feature allows you to reuse the same signature on all assets stored in the same cache path. Setting this value to 0 will strip off the filename in the URL (leaving the trailing slash) when calculating the checksum.
	UriLengthField string `json:"uriLengthField,omitempty"`
	// This is a query string parameter used to restrict the published URL to a specific user agent. Publishers can use this feature during the signing process to ensure that only a specific user agent can access the published content. You do not need to specify the user agent on the published URL. StackPath will use the HTTP User-Agent header value during signature validation.
	UserAgentField string `json:"userAgentField,omitempty"`
	Enabled bool `json:"enabled,omitempty"`
	// String of values delimited by a ',' character.
	MethodFilter string `json:"methodFilter,omitempty"`
	// String of values delimited by a ',' character.
	PathFilter string `json:"pathFilter,omitempty"`
	// String of values delimited by a ',' character.
	HeaderFilter string `json:"headerFilter,omitempty"`
}
