/*
 * Object Storage
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package object_storage

import (
	"encoding/json"
)

// StorageGenerateCredentialsResponse A response with new credentials
type StorageGenerateCredentialsResponse struct {
	// The ID for the access key
	AccessKey *string `json:"accessKey,omitempty"`
	// The secret key used to sign requests
	SecretKey *string `json:"secretKey,omitempty"`
}

// NewStorageGenerateCredentialsResponse instantiates a new StorageGenerateCredentialsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStorageGenerateCredentialsResponse() *StorageGenerateCredentialsResponse {
	this := StorageGenerateCredentialsResponse{}
	return &this
}

// NewStorageGenerateCredentialsResponseWithDefaults instantiates a new StorageGenerateCredentialsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStorageGenerateCredentialsResponseWithDefaults() *StorageGenerateCredentialsResponse {
	this := StorageGenerateCredentialsResponse{}
	return &this
}

// GetAccessKey returns the AccessKey field value if set, zero value otherwise.
func (o *StorageGenerateCredentialsResponse) GetAccessKey() string {
	if o == nil || o.AccessKey == nil {
		var ret string
		return ret
	}
	return *o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageGenerateCredentialsResponse) GetAccessKeyOk() (*string, bool) {
	if o == nil || o.AccessKey == nil {
		return nil, false
	}
	return o.AccessKey, true
}

// HasAccessKey returns a boolean if a field has been set.
func (o *StorageGenerateCredentialsResponse) HasAccessKey() bool {
	if o != nil && o.AccessKey != nil {
		return true
	}

	return false
}

// SetAccessKey gets a reference to the given string and assigns it to the AccessKey field.
func (o *StorageGenerateCredentialsResponse) SetAccessKey(v string) {
	o.AccessKey = &v
}

// GetSecretKey returns the SecretKey field value if set, zero value otherwise.
func (o *StorageGenerateCredentialsResponse) GetSecretKey() string {
	if o == nil || o.SecretKey == nil {
		var ret string
		return ret
	}
	return *o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StorageGenerateCredentialsResponse) GetSecretKeyOk() (*string, bool) {
	if o == nil || o.SecretKey == nil {
		return nil, false
	}
	return o.SecretKey, true
}

// HasSecretKey returns a boolean if a field has been set.
func (o *StorageGenerateCredentialsResponse) HasSecretKey() bool {
	if o != nil && o.SecretKey != nil {
		return true
	}

	return false
}

// SetSecretKey gets a reference to the given string and assigns it to the SecretKey field.
func (o *StorageGenerateCredentialsResponse) SetSecretKey(v string) {
	o.SecretKey = &v
}

func (o StorageGenerateCredentialsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AccessKey != nil {
		toSerialize["accessKey"] = o.AccessKey
	}
	if o.SecretKey != nil {
		toSerialize["secretKey"] = o.SecretKey
	}
	return json.Marshal(toSerialize)
}

type NullableStorageGenerateCredentialsResponse struct {
	value *StorageGenerateCredentialsResponse
	isSet bool
}

func (v NullableStorageGenerateCredentialsResponse) Get() *StorageGenerateCredentialsResponse {
	return v.value
}

func (v *NullableStorageGenerateCredentialsResponse) Set(val *StorageGenerateCredentialsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStorageGenerateCredentialsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStorageGenerateCredentialsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStorageGenerateCredentialsResponse(val *StorageGenerateCredentialsResponse) *NullableStorageGenerateCredentialsResponse {
	return &NullableStorageGenerateCredentialsResponse{value: val, isSet: true}
}

func (v NullableStorageGenerateCredentialsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStorageGenerateCredentialsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
