/*
 * Object Storage
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package object_storage
// StackpathRpcLocalizedMessageAllOf struct for StackpathRpcLocalizedMessageAllOf
type StackpathRpcLocalizedMessageAllOf struct {
	Locale string `json:"locale,omitempty"`
	Message string `json:"message,omitempty"`
}
