/*
 * Monitoring
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package monitoring
// V2CreateMonitorRequest struct for V2CreateMonitorRequest
type V2CreateMonitorRequest struct {
	// The monitor's name
	Name string `json:"name,omitempty"`
	// The IDs of locations to monitor from
	Locations []string `json:"locations,omitempty"`
	// How often a monitor should be checked.
	Interval string `json:"interval,omitempty"`
	// How long to wait before timing out a monitor check request to a service.
	Timeout string `json:"timeout,omitempty"`
	IpVersion V2IpVersion `json:"ipVersion,omitempty"`
	Http V2HttpConfiguration `json:"http,omitempty"`
	Tcp V2TcpConfiguration `json:"tcp,omitempty"`
	// Whether a monitor is enabled or not.
	Enabled bool `json:"enabled,omitempty"`
}
