/*
 * Monitoring
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package monitoring
// V2MonitorStatus The status of a monitor  - UNKNOWN: Unable to determine the status of the service being monitored. This is likely due to a new monitor that has not been checked yet.  - UP: The status of the service being monitored is up.  - DOWN: The status of the service being monitored is down.  - SLOW: The status of the service being monitored is slow. A service with a slow status means the service is up but responses are taking longer than 500 milliseconds.
type V2MonitorStatus string

// List of v2MonitorStatus
const (
	V2MONITORSTATUS_UNKNOWN V2MonitorStatus = "UNKNOWN"
	V2MONITORSTATUS_UP V2MonitorStatus = "UP"
	V2MONITORSTATUS_DOWN V2MonitorStatus = "DOWN"
	V2MONITORSTATUS_SLOW V2MonitorStatus = "SLOW"
)
