/*
 * Monitoring
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package monitoring
// UpdateMonitorRequestPatchHttpConfiguration The HTTP configuration for a monitor update request.
type UpdateMonitorRequestPatchHttpConfiguration struct {
	// The URL of the service that will be monitored.  The URL must begin with an HTTP scheme of 'http' or 'https'.
	Url string `json:"url,omitempty"`
	// The HTTP method used when the monitor makes a request to the service.
	Method string `json:"method,omitempty"`
	// A base64 encoded HTTP request body to use when a monitor checks the service.
	Body string `json:"body,omitempty"`
	Headers PatchHttpConfigurationHeaderValue `json:"headers,omitempty"`
	Basic UpdateMonitorRequestPatchHttpConfigurationBasicAuth `json:"basic,omitempty"`
	Digest UpdateMonitorRequestPatchHttpConfigurationDigestAuth `json:"digest,omitempty"`
	ClientCertificate UpdateMonitorRequestPatchHttpConfigurationClientCertificate `json:"clientCertificate,omitempty"`
	// A flag for validating a service's certificate.
	ValidateCertificate bool `json:"validateCertificate,omitempty"`
}
