/*
 * Monitoring
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package monitoring

import (
	"encoding/json"
)

// V2CreateMonitorResponse A response from a request to create a monitor.
type V2CreateMonitorResponse struct {
	Record *V2Monitor `json:"record,omitempty"`
}

// NewV2CreateMonitorResponse instantiates a new V2CreateMonitorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV2CreateMonitorResponse() *V2CreateMonitorResponse {
	this := V2CreateMonitorResponse{}
	return &this
}

// NewV2CreateMonitorResponseWithDefaults instantiates a new V2CreateMonitorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV2CreateMonitorResponseWithDefaults() *V2CreateMonitorResponse {
	this := V2CreateMonitorResponse{}
	return &this
}

// GetRecord returns the Record field value if set, zero value otherwise.
func (o *V2CreateMonitorResponse) GetRecord() V2Monitor {
	if o == nil || o.Record == nil {
		var ret V2Monitor
		return ret
	}
	return *o.Record
}

// GetRecordOk returns a tuple with the Record field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V2CreateMonitorResponse) GetRecordOk() (*V2Monitor, bool) {
	if o == nil || o.Record == nil {
		return nil, false
	}
	return o.Record, true
}

// HasRecord returns a boolean if a field has been set.
func (o *V2CreateMonitorResponse) HasRecord() bool {
	if o != nil && o.Record != nil {
		return true
	}

	return false
}

// SetRecord gets a reference to the given V2Monitor and assigns it to the Record field.
func (o *V2CreateMonitorResponse) SetRecord(v V2Monitor) {
	o.Record = &v
}

func (o V2CreateMonitorResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Record != nil {
		toSerialize["record"] = o.Record
	}
	return json.Marshal(toSerialize)
}

type NullableV2CreateMonitorResponse struct {
	value *V2CreateMonitorResponse
	isSet bool
}

func (v NullableV2CreateMonitorResponse) Get() *V2CreateMonitorResponse {
	return v.value
}

func (v *NullableV2CreateMonitorResponse) Set(val *V2CreateMonitorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV2CreateMonitorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV2CreateMonitorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV2CreateMonitorResponse(val *V2CreateMonitorResponse) *NullableV2CreateMonitorResponse {
	return &NullableV2CreateMonitorResponse{value: val, isSet: true}
}

func (v NullableV2CreateMonitorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV2CreateMonitorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
