/*
 * Monitoring
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package monitoring
// V2CreateMonitorResponse A response from a request to create a monitor.
type V2CreateMonitorResponse struct {
	Record V2Monitor `json:"record,omitempty"`
}
