/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf

import (
	"encoding/json"
	"time"
)

// WafRequestDetails A request that was inspected by the WAF
type WafRequestDetails struct {
	// The WAF request's unique identifier
	Id *string `json:"id,omitempty"`
	// The path of the requested URL
	Path *string `json:"path,omitempty"`
	Method *WafHttpMethod `json:"method,omitempty"`
	Action *WafRequestAction `json:"action,omitempty"`
	// The unique ID of the WAF rule that triggered the action against the WAF request
	RuleId *string `json:"ruleId,omitempty"`
	// The name of the WAF rule triggered by the request
	RuleName *string `json:"ruleName,omitempty"`
	UserAgent *WafRequestDetailsUserAgent `json:"userAgent,omitempty"`
	Network *WafRequestDetailsNetwork `json:"network,omitempty"`
	// When the WAF request occurred
	RequestTime *time.Time `json:"requestTime,omitempty"`
	// The WAF request's user-facing identifier  Reference IDs are displayed to the end user when the WAF blocks a request to a site. Please note that a request's ID and reference ID are different.
	ReferenceId *string `json:"referenceId,omitempty"`
	// The content type of the WAF request
	ContentType *string `json:"contentType,omitempty"`
	// The HTTP scheme of the WAF request
	Scheme *string `json:"scheme,omitempty"`
	// The HTTP status code of the WAF request
	HttpStatusCode *string `json:"httpStatusCode,omitempty"`
	// The HTTP version of the WAF request
	HttpVersion *string `json:"httpVersion,omitempty"`
	// Aspects of a WAF request
	Tags *map[string]RequestDetailsTags `json:"tags,omitempty"`
	// The time it took the WAF to process the WAF request
	ResponseTime *string `json:"responseTime,omitempty"`
	// The HTTP request headers of the WAF request
	RequestHeaders *map[string]string `json:"requestHeaders,omitempty"`
	// The ID of the of challenge that was generated for the WAF request
	IncidentId *string `json:"incidentId,omitempty"`
	RequestType *RequestDetailsRequestType `json:"requestType,omitempty"`
	// The number of WAF requests in the session
	SessionRequestCount *string `json:"sessionRequestCount,omitempty"`
}

// NewWafRequestDetails instantiates a new WafRequestDetails object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWafRequestDetails() *WafRequestDetails {
	this := WafRequestDetails{}
	var method WafHttpMethod = "METHOD_UNSPECIFIED"
	this.Method = &method
	var action WafRequestAction = "ACTION_UNSPECIFIED"
	this.Action = &action
	var requestType RequestDetailsRequestType = "API"
	this.RequestType = &requestType
	return &this
}

// NewWafRequestDetailsWithDefaults instantiates a new WafRequestDetails object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWafRequestDetailsWithDefaults() *WafRequestDetails {
	this := WafRequestDetails{}
	var method WafHttpMethod = "METHOD_UNSPECIFIED"
	this.Method = &method
	var action WafRequestAction = "ACTION_UNSPECIFIED"
	this.Action = &action
	var requestType RequestDetailsRequestType = "API"
	this.RequestType = &requestType
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *WafRequestDetails) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *WafRequestDetails) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *WafRequestDetails) SetId(v string) {
	o.Id = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *WafRequestDetails) GetPath() string {
	if o == nil || o.Path == nil {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetPathOk() (*string, bool) {
	if o == nil || o.Path == nil {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *WafRequestDetails) HasPath() bool {
	if o != nil && o.Path != nil {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *WafRequestDetails) SetPath(v string) {
	o.Path = &v
}

// GetMethod returns the Method field value if set, zero value otherwise.
func (o *WafRequestDetails) GetMethod() WafHttpMethod {
	if o == nil || o.Method == nil {
		var ret WafHttpMethod
		return ret
	}
	return *o.Method
}

// GetMethodOk returns a tuple with the Method field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetMethodOk() (*WafHttpMethod, bool) {
	if o == nil || o.Method == nil {
		return nil, false
	}
	return o.Method, true
}

// HasMethod returns a boolean if a field has been set.
func (o *WafRequestDetails) HasMethod() bool {
	if o != nil && o.Method != nil {
		return true
	}

	return false
}

// SetMethod gets a reference to the given WafHttpMethod and assigns it to the Method field.
func (o *WafRequestDetails) SetMethod(v WafHttpMethod) {
	o.Method = &v
}

// GetAction returns the Action field value if set, zero value otherwise.
func (o *WafRequestDetails) GetAction() WafRequestAction {
	if o == nil || o.Action == nil {
		var ret WafRequestAction
		return ret
	}
	return *o.Action
}

// GetActionOk returns a tuple with the Action field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetActionOk() (*WafRequestAction, bool) {
	if o == nil || o.Action == nil {
		return nil, false
	}
	return o.Action, true
}

// HasAction returns a boolean if a field has been set.
func (o *WafRequestDetails) HasAction() bool {
	if o != nil && o.Action != nil {
		return true
	}

	return false
}

// SetAction gets a reference to the given WafRequestAction and assigns it to the Action field.
func (o *WafRequestDetails) SetAction(v WafRequestAction) {
	o.Action = &v
}

// GetRuleId returns the RuleId field value if set, zero value otherwise.
func (o *WafRequestDetails) GetRuleId() string {
	if o == nil || o.RuleId == nil {
		var ret string
		return ret
	}
	return *o.RuleId
}

// GetRuleIdOk returns a tuple with the RuleId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetRuleIdOk() (*string, bool) {
	if o == nil || o.RuleId == nil {
		return nil, false
	}
	return o.RuleId, true
}

// HasRuleId returns a boolean if a field has been set.
func (o *WafRequestDetails) HasRuleId() bool {
	if o != nil && o.RuleId != nil {
		return true
	}

	return false
}

// SetRuleId gets a reference to the given string and assigns it to the RuleId field.
func (o *WafRequestDetails) SetRuleId(v string) {
	o.RuleId = &v
}

// GetRuleName returns the RuleName field value if set, zero value otherwise.
func (o *WafRequestDetails) GetRuleName() string {
	if o == nil || o.RuleName == nil {
		var ret string
		return ret
	}
	return *o.RuleName
}

// GetRuleNameOk returns a tuple with the RuleName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetRuleNameOk() (*string, bool) {
	if o == nil || o.RuleName == nil {
		return nil, false
	}
	return o.RuleName, true
}

// HasRuleName returns a boolean if a field has been set.
func (o *WafRequestDetails) HasRuleName() bool {
	if o != nil && o.RuleName != nil {
		return true
	}

	return false
}

// SetRuleName gets a reference to the given string and assigns it to the RuleName field.
func (o *WafRequestDetails) SetRuleName(v string) {
	o.RuleName = &v
}

// GetUserAgent returns the UserAgent field value if set, zero value otherwise.
func (o *WafRequestDetails) GetUserAgent() WafRequestDetailsUserAgent {
	if o == nil || o.UserAgent == nil {
		var ret WafRequestDetailsUserAgent
		return ret
	}
	return *o.UserAgent
}

// GetUserAgentOk returns a tuple with the UserAgent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetUserAgentOk() (*WafRequestDetailsUserAgent, bool) {
	if o == nil || o.UserAgent == nil {
		return nil, false
	}
	return o.UserAgent, true
}

// HasUserAgent returns a boolean if a field has been set.
func (o *WafRequestDetails) HasUserAgent() bool {
	if o != nil && o.UserAgent != nil {
		return true
	}

	return false
}

// SetUserAgent gets a reference to the given WafRequestDetailsUserAgent and assigns it to the UserAgent field.
func (o *WafRequestDetails) SetUserAgent(v WafRequestDetailsUserAgent) {
	o.UserAgent = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *WafRequestDetails) GetNetwork() WafRequestDetailsNetwork {
	if o == nil || o.Network == nil {
		var ret WafRequestDetailsNetwork
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetNetworkOk() (*WafRequestDetailsNetwork, bool) {
	if o == nil || o.Network == nil {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *WafRequestDetails) HasNetwork() bool {
	if o != nil && o.Network != nil {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given WafRequestDetailsNetwork and assigns it to the Network field.
func (o *WafRequestDetails) SetNetwork(v WafRequestDetailsNetwork) {
	o.Network = &v
}

// GetRequestTime returns the RequestTime field value if set, zero value otherwise.
func (o *WafRequestDetails) GetRequestTime() time.Time {
	if o == nil || o.RequestTime == nil {
		var ret time.Time
		return ret
	}
	return *o.RequestTime
}

// GetRequestTimeOk returns a tuple with the RequestTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetRequestTimeOk() (*time.Time, bool) {
	if o == nil || o.RequestTime == nil {
		return nil, false
	}
	return o.RequestTime, true
}

// HasRequestTime returns a boolean if a field has been set.
func (o *WafRequestDetails) HasRequestTime() bool {
	if o != nil && o.RequestTime != nil {
		return true
	}

	return false
}

// SetRequestTime gets a reference to the given time.Time and assigns it to the RequestTime field.
func (o *WafRequestDetails) SetRequestTime(v time.Time) {
	o.RequestTime = &v
}

// GetReferenceId returns the ReferenceId field value if set, zero value otherwise.
func (o *WafRequestDetails) GetReferenceId() string {
	if o == nil || o.ReferenceId == nil {
		var ret string
		return ret
	}
	return *o.ReferenceId
}

// GetReferenceIdOk returns a tuple with the ReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetReferenceIdOk() (*string, bool) {
	if o == nil || o.ReferenceId == nil {
		return nil, false
	}
	return o.ReferenceId, true
}

// HasReferenceId returns a boolean if a field has been set.
func (o *WafRequestDetails) HasReferenceId() bool {
	if o != nil && o.ReferenceId != nil {
		return true
	}

	return false
}

// SetReferenceId gets a reference to the given string and assigns it to the ReferenceId field.
func (o *WafRequestDetails) SetReferenceId(v string) {
	o.ReferenceId = &v
}

// GetContentType returns the ContentType field value if set, zero value otherwise.
func (o *WafRequestDetails) GetContentType() string {
	if o == nil || o.ContentType == nil {
		var ret string
		return ret
	}
	return *o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetContentTypeOk() (*string, bool) {
	if o == nil || o.ContentType == nil {
		return nil, false
	}
	return o.ContentType, true
}

// HasContentType returns a boolean if a field has been set.
func (o *WafRequestDetails) HasContentType() bool {
	if o != nil && o.ContentType != nil {
		return true
	}

	return false
}

// SetContentType gets a reference to the given string and assigns it to the ContentType field.
func (o *WafRequestDetails) SetContentType(v string) {
	o.ContentType = &v
}

// GetScheme returns the Scheme field value if set, zero value otherwise.
func (o *WafRequestDetails) GetScheme() string {
	if o == nil || o.Scheme == nil {
		var ret string
		return ret
	}
	return *o.Scheme
}

// GetSchemeOk returns a tuple with the Scheme field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetSchemeOk() (*string, bool) {
	if o == nil || o.Scheme == nil {
		return nil, false
	}
	return o.Scheme, true
}

// HasScheme returns a boolean if a field has been set.
func (o *WafRequestDetails) HasScheme() bool {
	if o != nil && o.Scheme != nil {
		return true
	}

	return false
}

// SetScheme gets a reference to the given string and assigns it to the Scheme field.
func (o *WafRequestDetails) SetScheme(v string) {
	o.Scheme = &v
}

// GetHttpStatusCode returns the HttpStatusCode field value if set, zero value otherwise.
func (o *WafRequestDetails) GetHttpStatusCode() string {
	if o == nil || o.HttpStatusCode == nil {
		var ret string
		return ret
	}
	return *o.HttpStatusCode
}

// GetHttpStatusCodeOk returns a tuple with the HttpStatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetHttpStatusCodeOk() (*string, bool) {
	if o == nil || o.HttpStatusCode == nil {
		return nil, false
	}
	return o.HttpStatusCode, true
}

// HasHttpStatusCode returns a boolean if a field has been set.
func (o *WafRequestDetails) HasHttpStatusCode() bool {
	if o != nil && o.HttpStatusCode != nil {
		return true
	}

	return false
}

// SetHttpStatusCode gets a reference to the given string and assigns it to the HttpStatusCode field.
func (o *WafRequestDetails) SetHttpStatusCode(v string) {
	o.HttpStatusCode = &v
}

// GetHttpVersion returns the HttpVersion field value if set, zero value otherwise.
func (o *WafRequestDetails) GetHttpVersion() string {
	if o == nil || o.HttpVersion == nil {
		var ret string
		return ret
	}
	return *o.HttpVersion
}

// GetHttpVersionOk returns a tuple with the HttpVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetHttpVersionOk() (*string, bool) {
	if o == nil || o.HttpVersion == nil {
		return nil, false
	}
	return o.HttpVersion, true
}

// HasHttpVersion returns a boolean if a field has been set.
func (o *WafRequestDetails) HasHttpVersion() bool {
	if o != nil && o.HttpVersion != nil {
		return true
	}

	return false
}

// SetHttpVersion gets a reference to the given string and assigns it to the HttpVersion field.
func (o *WafRequestDetails) SetHttpVersion(v string) {
	o.HttpVersion = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *WafRequestDetails) GetTags() map[string]RequestDetailsTags {
	if o == nil || o.Tags == nil {
		var ret map[string]RequestDetailsTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetTagsOk() (*map[string]RequestDetailsTags, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *WafRequestDetails) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given map[string]RequestDetailsTags and assigns it to the Tags field.
func (o *WafRequestDetails) SetTags(v map[string]RequestDetailsTags) {
	o.Tags = &v
}

// GetResponseTime returns the ResponseTime field value if set, zero value otherwise.
func (o *WafRequestDetails) GetResponseTime() string {
	if o == nil || o.ResponseTime == nil {
		var ret string
		return ret
	}
	return *o.ResponseTime
}

// GetResponseTimeOk returns a tuple with the ResponseTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetResponseTimeOk() (*string, bool) {
	if o == nil || o.ResponseTime == nil {
		return nil, false
	}
	return o.ResponseTime, true
}

// HasResponseTime returns a boolean if a field has been set.
func (o *WafRequestDetails) HasResponseTime() bool {
	if o != nil && o.ResponseTime != nil {
		return true
	}

	return false
}

// SetResponseTime gets a reference to the given string and assigns it to the ResponseTime field.
func (o *WafRequestDetails) SetResponseTime(v string) {
	o.ResponseTime = &v
}

// GetRequestHeaders returns the RequestHeaders field value if set, zero value otherwise.
func (o *WafRequestDetails) GetRequestHeaders() map[string]string {
	if o == nil || o.RequestHeaders == nil {
		var ret map[string]string
		return ret
	}
	return *o.RequestHeaders
}

// GetRequestHeadersOk returns a tuple with the RequestHeaders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetRequestHeadersOk() (*map[string]string, bool) {
	if o == nil || o.RequestHeaders == nil {
		return nil, false
	}
	return o.RequestHeaders, true
}

// HasRequestHeaders returns a boolean if a field has been set.
func (o *WafRequestDetails) HasRequestHeaders() bool {
	if o != nil && o.RequestHeaders != nil {
		return true
	}

	return false
}

// SetRequestHeaders gets a reference to the given map[string]string and assigns it to the RequestHeaders field.
func (o *WafRequestDetails) SetRequestHeaders(v map[string]string) {
	o.RequestHeaders = &v
}

// GetIncidentId returns the IncidentId field value if set, zero value otherwise.
func (o *WafRequestDetails) GetIncidentId() string {
	if o == nil || o.IncidentId == nil {
		var ret string
		return ret
	}
	return *o.IncidentId
}

// GetIncidentIdOk returns a tuple with the IncidentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetIncidentIdOk() (*string, bool) {
	if o == nil || o.IncidentId == nil {
		return nil, false
	}
	return o.IncidentId, true
}

// HasIncidentId returns a boolean if a field has been set.
func (o *WafRequestDetails) HasIncidentId() bool {
	if o != nil && o.IncidentId != nil {
		return true
	}

	return false
}

// SetIncidentId gets a reference to the given string and assigns it to the IncidentId field.
func (o *WafRequestDetails) SetIncidentId(v string) {
	o.IncidentId = &v
}

// GetRequestType returns the RequestType field value if set, zero value otherwise.
func (o *WafRequestDetails) GetRequestType() RequestDetailsRequestType {
	if o == nil || o.RequestType == nil {
		var ret RequestDetailsRequestType
		return ret
	}
	return *o.RequestType
}

// GetRequestTypeOk returns a tuple with the RequestType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetRequestTypeOk() (*RequestDetailsRequestType, bool) {
	if o == nil || o.RequestType == nil {
		return nil, false
	}
	return o.RequestType, true
}

// HasRequestType returns a boolean if a field has been set.
func (o *WafRequestDetails) HasRequestType() bool {
	if o != nil && o.RequestType != nil {
		return true
	}

	return false
}

// SetRequestType gets a reference to the given RequestDetailsRequestType and assigns it to the RequestType field.
func (o *WafRequestDetails) SetRequestType(v RequestDetailsRequestType) {
	o.RequestType = &v
}

// GetSessionRequestCount returns the SessionRequestCount field value if set, zero value otherwise.
func (o *WafRequestDetails) GetSessionRequestCount() string {
	if o == nil || o.SessionRequestCount == nil {
		var ret string
		return ret
	}
	return *o.SessionRequestCount
}

// GetSessionRequestCountOk returns a tuple with the SessionRequestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafRequestDetails) GetSessionRequestCountOk() (*string, bool) {
	if o == nil || o.SessionRequestCount == nil {
		return nil, false
	}
	return o.SessionRequestCount, true
}

// HasSessionRequestCount returns a boolean if a field has been set.
func (o *WafRequestDetails) HasSessionRequestCount() bool {
	if o != nil && o.SessionRequestCount != nil {
		return true
	}

	return false
}

// SetSessionRequestCount gets a reference to the given string and assigns it to the SessionRequestCount field.
func (o *WafRequestDetails) SetSessionRequestCount(v string) {
	o.SessionRequestCount = &v
}

func (o WafRequestDetails) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Path != nil {
		toSerialize["path"] = o.Path
	}
	if o.Method != nil {
		toSerialize["method"] = o.Method
	}
	if o.Action != nil {
		toSerialize["action"] = o.Action
	}
	if o.RuleId != nil {
		toSerialize["ruleId"] = o.RuleId
	}
	if o.RuleName != nil {
		toSerialize["ruleName"] = o.RuleName
	}
	if o.UserAgent != nil {
		toSerialize["userAgent"] = o.UserAgent
	}
	if o.Network != nil {
		toSerialize["network"] = o.Network
	}
	if o.RequestTime != nil {
		toSerialize["requestTime"] = o.RequestTime
	}
	if o.ReferenceId != nil {
		toSerialize["referenceId"] = o.ReferenceId
	}
	if o.ContentType != nil {
		toSerialize["contentType"] = o.ContentType
	}
	if o.Scheme != nil {
		toSerialize["scheme"] = o.Scheme
	}
	if o.HttpStatusCode != nil {
		toSerialize["httpStatusCode"] = o.HttpStatusCode
	}
	if o.HttpVersion != nil {
		toSerialize["httpVersion"] = o.HttpVersion
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.ResponseTime != nil {
		toSerialize["responseTime"] = o.ResponseTime
	}
	if o.RequestHeaders != nil {
		toSerialize["requestHeaders"] = o.RequestHeaders
	}
	if o.IncidentId != nil {
		toSerialize["incidentId"] = o.IncidentId
	}
	if o.RequestType != nil {
		toSerialize["requestType"] = o.RequestType
	}
	if o.SessionRequestCount != nil {
		toSerialize["sessionRequestCount"] = o.SessionRequestCount
	}
	return json.Marshal(toSerialize)
}

type NullableWafRequestDetails struct {
	value *WafRequestDetails
	isSet bool
}

func (v NullableWafRequestDetails) Get() *WafRequestDetails {
	return v.value
}

func (v *NullableWafRequestDetails) Set(val *WafRequestDetails) {
	v.value = val
	v.isSet = true
}

func (v NullableWafRequestDetails) IsSet() bool {
	return v.isSet
}

func (v *NullableWafRequestDetails) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWafRequestDetails(val *WafRequestDetails) *NullableWafRequestDetails {
	return &NullableWafRequestDetails{value: val, isSet: true}
}

func (v NullableWafRequestDetails) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWafRequestDetails) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
