/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf

import (
	"encoding/json"
)

// WafEventNetwork A WAF event's network related aspects
type WafEventNetwork struct {
	// The originating IP address
	Ip *string `json:"ip,omitempty"`
	// The long name of the country where the request originated from
	Country *string `json:"country,omitempty"`
	// The ISO 3166-1 alpha-2 code of the country where the request originated from
	CountryCode *string `json:"countryCode,omitempty"`
	// The organization that owns the originating IP address according to a WHOIS lookup
	Organization *string `json:"organization,omitempty"`
}

// NewWafEventNetwork instantiates a new WafEventNetwork object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWafEventNetwork() *WafEventNetwork {
	this := WafEventNetwork{}
	return &this
}

// NewWafEventNetworkWithDefaults instantiates a new WafEventNetwork object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWafEventNetworkWithDefaults() *WafEventNetwork {
	this := WafEventNetwork{}
	return &this
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *WafEventNetwork) GetIp() string {
	if o == nil || o.Ip == nil {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafEventNetwork) GetIpOk() (*string, bool) {
	if o == nil || o.Ip == nil {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *WafEventNetwork) HasIp() bool {
	if o != nil && o.Ip != nil {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *WafEventNetwork) SetIp(v string) {
	o.Ip = &v
}

// GetCountry returns the Country field value if set, zero value otherwise.
func (o *WafEventNetwork) GetCountry() string {
	if o == nil || o.Country == nil {
		var ret string
		return ret
	}
	return *o.Country
}

// GetCountryOk returns a tuple with the Country field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafEventNetwork) GetCountryOk() (*string, bool) {
	if o == nil || o.Country == nil {
		return nil, false
	}
	return o.Country, true
}

// HasCountry returns a boolean if a field has been set.
func (o *WafEventNetwork) HasCountry() bool {
	if o != nil && o.Country != nil {
		return true
	}

	return false
}

// SetCountry gets a reference to the given string and assigns it to the Country field.
func (o *WafEventNetwork) SetCountry(v string) {
	o.Country = &v
}

// GetCountryCode returns the CountryCode field value if set, zero value otherwise.
func (o *WafEventNetwork) GetCountryCode() string {
	if o == nil || o.CountryCode == nil {
		var ret string
		return ret
	}
	return *o.CountryCode
}

// GetCountryCodeOk returns a tuple with the CountryCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafEventNetwork) GetCountryCodeOk() (*string, bool) {
	if o == nil || o.CountryCode == nil {
		return nil, false
	}
	return o.CountryCode, true
}

// HasCountryCode returns a boolean if a field has been set.
func (o *WafEventNetwork) HasCountryCode() bool {
	if o != nil && o.CountryCode != nil {
		return true
	}

	return false
}

// SetCountryCode gets a reference to the given string and assigns it to the CountryCode field.
func (o *WafEventNetwork) SetCountryCode(v string) {
	o.CountryCode = &v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *WafEventNetwork) GetOrganization() string {
	if o == nil || o.Organization == nil {
		var ret string
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafEventNetwork) GetOrganizationOk() (*string, bool) {
	if o == nil || o.Organization == nil {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *WafEventNetwork) HasOrganization() bool {
	if o != nil && o.Organization != nil {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given string and assigns it to the Organization field.
func (o *WafEventNetwork) SetOrganization(v string) {
	o.Organization = &v
}

func (o WafEventNetwork) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Ip != nil {
		toSerialize["ip"] = o.Ip
	}
	if o.Country != nil {
		toSerialize["country"] = o.Country
	}
	if o.CountryCode != nil {
		toSerialize["countryCode"] = o.CountryCode
	}
	if o.Organization != nil {
		toSerialize["organization"] = o.Organization
	}
	return json.Marshal(toSerialize)
}

type NullableWafEventNetwork struct {
	value *WafEventNetwork
	isSet bool
}

func (v NullableWafEventNetwork) Get() *WafEventNetwork {
	return v.value
}

func (v *NullableWafEventNetwork) Set(val *WafEventNetwork) {
	v.value = val
	v.isSet = true
}

func (v NullableWafEventNetwork) IsSet() bool {
	return v.isSet
}

func (v *NullableWafEventNetwork) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWafEventNetwork(val *WafEventNetwork) *NullableWafEventNetwork {
	return &NullableWafEventNetwork{value: val, isSet: true}
}

func (v NullableWafEventNetwork) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWafEventNetwork) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
