/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf

import (
	"encoding/json"
)

// ConditionHeaderExistsCondition Match when an incoming request header is present
type ConditionHeaderExistsCondition struct {
	// The request header name
	Header *string `json:"header,omitempty"`
}

// NewConditionHeaderExistsCondition instantiates a new ConditionHeaderExistsCondition object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConditionHeaderExistsCondition() *ConditionHeaderExistsCondition {
	this := ConditionHeaderExistsCondition{}
	return &this
}

// NewConditionHeaderExistsConditionWithDefaults instantiates a new ConditionHeaderExistsCondition object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConditionHeaderExistsConditionWithDefaults() *ConditionHeaderExistsCondition {
	this := ConditionHeaderExistsCondition{}
	return &this
}

// GetHeader returns the Header field value if set, zero value otherwise.
func (o *ConditionHeaderExistsCondition) GetHeader() string {
	if o == nil || o.Header == nil {
		var ret string
		return ret
	}
	return *o.Header
}

// GetHeaderOk returns a tuple with the Header field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConditionHeaderExistsCondition) GetHeaderOk() (*string, bool) {
	if o == nil || o.Header == nil {
		return nil, false
	}
	return o.Header, true
}

// HasHeader returns a boolean if a field has been set.
func (o *ConditionHeaderExistsCondition) HasHeader() bool {
	if o != nil && o.Header != nil {
		return true
	}

	return false
}

// SetHeader gets a reference to the given string and assigns it to the Header field.
func (o *ConditionHeaderExistsCondition) SetHeader(v string) {
	o.Header = &v
}

func (o ConditionHeaderExistsCondition) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Header != nil {
		toSerialize["header"] = o.Header
	}
	return json.Marshal(toSerialize)
}

type NullableConditionHeaderExistsCondition struct {
	value *ConditionHeaderExistsCondition
	isSet bool
}

func (v NullableConditionHeaderExistsCondition) Get() *ConditionHeaderExistsCondition {
	return v.value
}

func (v *NullableConditionHeaderExistsCondition) Set(val *ConditionHeaderExistsCondition) {
	v.value = val
	v.isSet = true
}

func (v NullableConditionHeaderExistsCondition) IsSet() bool {
	return v.isSet
}

func (v *NullableConditionHeaderExistsCondition) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConditionHeaderExistsCondition(val *ConditionHeaderExistsCondition) *NullableConditionHeaderExistsCondition {
	return &NullableConditionHeaderExistsCondition{value: val, isSet: true}
}

func (v NullableConditionHeaderExistsCondition) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConditionHeaderExistsCondition) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
