/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf

import (
	"encoding/json"
)

// WafGetCertificateVerificationDetailsResponse A response from a request to retrieve an SSL certificate's manual verification details
type WafGetCertificateVerificationDetailsResponse struct {
	// Whether or not the end user must provide their own certificate verification
	ManualVerificationRequired *bool `json:"manualVerificationRequired,omitempty"`
	// An SSL certificate's verification requirements
	VerificationRequirements *[]WafVerificationRequirements `json:"verificationRequirements,omitempty"`
}

// NewWafGetCertificateVerificationDetailsResponse instantiates a new WafGetCertificateVerificationDetailsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWafGetCertificateVerificationDetailsResponse() *WafGetCertificateVerificationDetailsResponse {
	this := WafGetCertificateVerificationDetailsResponse{}
	return &this
}

// NewWafGetCertificateVerificationDetailsResponseWithDefaults instantiates a new WafGetCertificateVerificationDetailsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWafGetCertificateVerificationDetailsResponseWithDefaults() *WafGetCertificateVerificationDetailsResponse {
	this := WafGetCertificateVerificationDetailsResponse{}
	return &this
}

// GetManualVerificationRequired returns the ManualVerificationRequired field value if set, zero value otherwise.
func (o *WafGetCertificateVerificationDetailsResponse) GetManualVerificationRequired() bool {
	if o == nil || o.ManualVerificationRequired == nil {
		var ret bool
		return ret
	}
	return *o.ManualVerificationRequired
}

// GetManualVerificationRequiredOk returns a tuple with the ManualVerificationRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafGetCertificateVerificationDetailsResponse) GetManualVerificationRequiredOk() (*bool, bool) {
	if o == nil || o.ManualVerificationRequired == nil {
		return nil, false
	}
	return o.ManualVerificationRequired, true
}

// HasManualVerificationRequired returns a boolean if a field has been set.
func (o *WafGetCertificateVerificationDetailsResponse) HasManualVerificationRequired() bool {
	if o != nil && o.ManualVerificationRequired != nil {
		return true
	}

	return false
}

// SetManualVerificationRequired gets a reference to the given bool and assigns it to the ManualVerificationRequired field.
func (o *WafGetCertificateVerificationDetailsResponse) SetManualVerificationRequired(v bool) {
	o.ManualVerificationRequired = &v
}

// GetVerificationRequirements returns the VerificationRequirements field value if set, zero value otherwise.
func (o *WafGetCertificateVerificationDetailsResponse) GetVerificationRequirements() []WafVerificationRequirements {
	if o == nil || o.VerificationRequirements == nil {
		var ret []WafVerificationRequirements
		return ret
	}
	return *o.VerificationRequirements
}

// GetVerificationRequirementsOk returns a tuple with the VerificationRequirements field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WafGetCertificateVerificationDetailsResponse) GetVerificationRequirementsOk() (*[]WafVerificationRequirements, bool) {
	if o == nil || o.VerificationRequirements == nil {
		return nil, false
	}
	return o.VerificationRequirements, true
}

// HasVerificationRequirements returns a boolean if a field has been set.
func (o *WafGetCertificateVerificationDetailsResponse) HasVerificationRequirements() bool {
	if o != nil && o.VerificationRequirements != nil {
		return true
	}

	return false
}

// SetVerificationRequirements gets a reference to the given []WafVerificationRequirements and assigns it to the VerificationRequirements field.
func (o *WafGetCertificateVerificationDetailsResponse) SetVerificationRequirements(v []WafVerificationRequirements) {
	o.VerificationRequirements = &v
}

func (o WafGetCertificateVerificationDetailsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ManualVerificationRequired != nil {
		toSerialize["manualVerificationRequired"] = o.ManualVerificationRequired
	}
	if o.VerificationRequirements != nil {
		toSerialize["verificationRequirements"] = o.VerificationRequirements
	}
	return json.Marshal(toSerialize)
}

type NullableWafGetCertificateVerificationDetailsResponse struct {
	value *WafGetCertificateVerificationDetailsResponse
	isSet bool
}

func (v NullableWafGetCertificateVerificationDetailsResponse) Get() *WafGetCertificateVerificationDetailsResponse {
	return v.value
}

func (v *NullableWafGetCertificateVerificationDetailsResponse) Set(val *WafGetCertificateVerificationDetailsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableWafGetCertificateVerificationDetailsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableWafGetCertificateVerificationDetailsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWafGetCertificateVerificationDetailsResponse(val *WafGetCertificateVerificationDetailsResponse) *NullableWafGetCertificateVerificationDetailsResponse {
	return &NullableWafGetCertificateVerificationDetailsResponse{value: val, isSet: true}
}

func (v NullableWafGetCertificateVerificationDetailsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWafGetCertificateVerificationDetailsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
