/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf
// StackpathRpcRetryInfoAllOf struct for StackpathRpcRetryInfoAllOf
type StackpathRpcRetryInfoAllOf struct {
	RetryDelay string `json:"retryDelay,omitempty"`
}
