/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf

import (
	"encoding/json"
)

// WafRuleAction The actions that the WAF takes when a rule is triggered  - BLOCK: The WAF blocked the request  - ALLOW: The WAF allowed the request  - CAPTCHA: The WAF presented the user with a captcha  - HANDSHAKE: The WAF performed automatic browser validation  - MONITOR: The WAF monitored the request but took no action  - GATEWAY: The WAF performed extended automatic browser validation
type WafRuleAction string

// List of wafRuleAction
const (
	WAFRULEACTION_BLOCK WafRuleAction = "BLOCK"
	WAFRULEACTION_ALLOW WafRuleAction = "ALLOW"
	WAFRULEACTION_CAPTCHA WafRuleAction = "CAPTCHA"
	WAFRULEACTION_HANDSHAKE WafRuleAction = "HANDSHAKE"
	WAFRULEACTION_MONITOR WafRuleAction = "MONITOR"
	WAFRULEACTION_GATEWAY WafRuleAction = "GATEWAY"
)

// Ptr returns reference to wafRuleAction value
func (v WafRuleAction) Ptr() *WafRuleAction {
	return &v
}


type NullableWafRuleAction struct {
	value *WafRuleAction
	isSet bool
}

func (v NullableWafRuleAction) Get() *WafRuleAction {
	return v.value
}

func (v *NullableWafRuleAction) Set(val *WafRuleAction) {
	v.value = val
	v.isSet = true
}

func (v NullableWafRuleAction) IsSet() bool {
	return v.isSet
}

func (v *NullableWafRuleAction) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWafRuleAction(val *WafRuleAction) *NullableWafRuleAction {
	return &NullableWafRuleAction{value: val, isSet: true}
}

func (v NullableWafRuleAction) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWafRuleAction) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
