/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf
// WafGetRequestsResponse The requested WAF requests
type WafGetRequestsResponse struct {
	PageInfo PaginationPageInfo `json:"pageInfo,omitempty"`
	// The requested information about a WAF site's requests
	Results []SchemawafRequest `json:"results,omitempty"`
}
