/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf

import (
	"encoding/json"
)

// EventWafRequestType the model 'EventWafRequestType'
type EventWafRequestType string

// List of EventWafRequestType
const (
	EVENTWAFREQUESTTYPE_CHALLENGE EventWafRequestType = "CHALLENGE"
	EVENTWAFREQUESTTYPE_BLOCK EventWafRequestType = "BLOCK"
)

// Ptr returns reference to EventWafRequestType value
func (v EventWafRequestType) Ptr() *EventWafRequestType {
	return &v
}


type NullableEventWafRequestType struct {
	value *EventWafRequestType
	isSet bool
}

func (v NullableEventWafRequestType) Get() *EventWafRequestType {
	return v.value
}

func (v *NullableEventWafRequestType) Set(val *EventWafRequestType) {
	v.value = val
	v.isSet = true
}

func (v NullableEventWafRequestType) IsSet() bool {
	return v.isSet
}

func (v *NullableEventWafRequestType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEventWafRequestType(val *EventWafRequestType) *NullableEventWafRequestType {
	return &NullableEventWafRequestType{value: val, isSet: true}
}

func (v NullableEventWafRequestType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEventWafRequestType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
