/*
 * Web Application Firewall
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package waf
// WafUpdateCertificateResponse A response from a request to update an SSL certificate
type WafUpdateCertificateResponse struct {
	Certificate WafCertificate `json:"certificate,omitempty"`
}
