/*
 * DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dns
// StackpathRpcBadRequestAllOf struct for StackpathRpcBadRequestAllOf
type StackpathRpcBadRequestAllOf struct {
	FieldViolations []StackpathRpcBadRequestFieldViolation `json:"fieldViolations,omitempty"`
}
