/*
 * DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dns
// ZoneRecordType The resource record types supported by StackPath  - EMPTY: The resource record has no type  - A: The resource record translates a host to an IPv4 address  - AAAA: The resource record translates a host to an IPv6 address  - CNAME: The resource record aliases one name to another  - TXT: The resource record contains a descriptive string. Many applications use TXT records for configuration  - MX: The resource record defines a mail exchanger for the given host  - SRV: The resource record defines a service on the domain  - NS: The resource record describes a nameserver that serves its domain's zone and records
type ZoneRecordType string

// List of zoneRecordType
const (
	EMPTY ZoneRecordType = "EMPTY"
	A ZoneRecordType = "A"
	AAAA ZoneRecordType = "AAAA"
	CNAME ZoneRecordType = "CNAME"
	TXT ZoneRecordType = "TXT"
	MX ZoneRecordType = "MX"
	SRV ZoneRecordType = "SRV"
	NS ZoneRecordType = "NS"
)
