/*
 * DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dns
import (
	"time"
)
// ZoneZone A DNS zone  A zone represents an individual domain in StackPath's DNS infrastructure.
type ZoneZone struct {
	// The ID of the stack that a zone belongs to
	StackId string `json:"stackId,omitempty"`
	// The ID of the StackPath account that owns a zone
	AccountId string `json:"accountId,omitempty"`
	// A zone's unique ID
	Id string `json:"id,omitempty"`
	// A zone's name
	Domain string `json:"domain,omitempty"`
	// A zone's version number  Version numbers are incremented automatically when a zone is updated
	Version string `json:"version,omitempty"`
	// A key/value pair of user-defined labels for a zone  Zone labels are not processed by StackPath and are solely used for users to organize their DNS zones.
	Labels map[string]string `json:"labels,omitempty"`
	// The date a zone was created
	Created time.Time `json:"created,omitempty"`
	// The date a zone was last updated
	Updated time.Time `json:"updated,omitempty"`
	// The hostnames of the StackPath resolvers that host a zone  Every zone has multiple name servers assigned by StackPath upon creation for redundancy purposes.
	Nameservers []string `json:"nameservers,omitempty"`
	// The date a zone's nameservers were last audited by StackPath
	Verified time.Time `json:"verified,omitempty"`
	Status ZoneZoneStatus `json:"status,omitempty"`
	// Whether or not a zone has been disabled by the user
	Disabled bool `json:"disabled,omitempty"`
}
