/*
 * DNS
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dns
// ZoneCreateZoneResponse A response from a request to create a new DNS zone
type ZoneCreateZoneResponse struct {
	Zone ZoneZone `json:"zone,omitempty"`
}
