/*
 * Edge Compute Networking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute_networking
// V1Protocols An object of all supported protocols and any attributes for them
type V1Protocols struct {
	Tcp V1ProtocolTcp `json:"tcp,omitempty"`
	Udp V1ProtocolUdp `json:"udp,omitempty"`
	TcpUdp V1ProtocolTcpUdp `json:"tcpUdp,omitempty"`
	// ICMP protocol matching
	Icmp map[string]interface{} `json:"icmp,omitempty"`
	// Authentication Header (AH) protocol matching
	Ah map[string]interface{} `json:"ah,omitempty"`
	// Encapsulating Security Payload (ESP) protocol matching
	Esp map[string]interface{} `json:"esp,omitempty"`
	// Generic Routing Encapsulation (GRE) protocol matching
	Gre map[string]interface{} `json:"gre,omitempty"`
}
