/*
 * Edge Compute Networking
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute_networking
// StackpathRpcRequestInfo struct for StackpathRpcRequestInfo
type StackpathRpcRequestInfo struct {
	Type string `json:"@type"`
	RequestId string `json:"requestId,omitempty"`
	ServingData string `json:"servingData,omitempty"`
}
