/*
 * Accounts and Users
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package accounts-and-users

import (
	"encoding/json"
)

// IdentityCreateUserCredentialRequest struct for IdentityCreateUserCredentialRequest
type IdentityCreateUserCredentialRequest struct {
	// The name of the new API credentials
	Name *string `json:"name,omitempty"`
}

// NewIdentityCreateUserCredentialRequest instantiates a new IdentityCreateUserCredentialRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdentityCreateUserCredentialRequest() *IdentityCreateUserCredentialRequest {
	this := IdentityCreateUserCredentialRequest{}
	return &this
}

// NewIdentityCreateUserCredentialRequestWithDefaults instantiates a new IdentityCreateUserCredentialRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdentityCreateUserCredentialRequestWithDefaults() *IdentityCreateUserCredentialRequest {
	this := IdentityCreateUserCredentialRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *IdentityCreateUserCredentialRequest) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdentityCreateUserCredentialRequest) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *IdentityCreateUserCredentialRequest) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *IdentityCreateUserCredentialRequest) SetName(v string) {
	o.Name = &v
}

func (o IdentityCreateUserCredentialRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableIdentityCreateUserCredentialRequest struct {
	value *IdentityCreateUserCredentialRequest
	isSet bool
}

func (v NullableIdentityCreateUserCredentialRequest) Get() *IdentityCreateUserCredentialRequest {
	return v.value
}

func (v *NullableIdentityCreateUserCredentialRequest) Set(val *IdentityCreateUserCredentialRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableIdentityCreateUserCredentialRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableIdentityCreateUserCredentialRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdentityCreateUserCredentialRequest(val *IdentityCreateUserCredentialRequest) *NullableIdentityCreateUserCredentialRequest {
	return &NullableIdentityCreateUserCredentialRequest{value: val, isSet: true}
}

func (v NullableIdentityCreateUserCredentialRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdentityCreateUserCredentialRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
