/*
 * Stacks
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package stacks
// StackStackStatus A stack's status
type StackStackStatus string

// List of stackStackStatus
const (
	STACKSTACKSTATUS_PENDING StackStackStatus = "PENDING"
	STACKSTACKSTATUS_ACTIVE StackStackStatus = "ACTIVE"
	STACKSTACKSTATUS_DISABLED StackStackStatus = "DISABLED"
	STACKSTACKSTATUS_SUSPENDED StackStackStatus = "SUSPENDED"
	STACKSTACKSTATUS_BILLING_SUSPENDED StackStackStatus = "BILLING_SUSPENDED"
	STACKSTACKSTATUS_CANCELLED StackStackStatus = "CANCELLED"
	STACKSTACKSTATUS_DELETED StackStackStatus = "DELETED"
)
