/*
 * Accounts and Users
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package accounts_and_users
// IdentityTestIamPermissionsResponse A response from a request to test permissions on a StackPath account
type IdentityTestIamPermissionsResponse struct {
	// The ID of the StackPath account the permissions were tested on
	AccountId string `json:"accountId,omitempty"`
	// The set of permissions that the calling user does have on the account
	Permissions []string `json:"permissions,omitempty"`
}
