/*
 * Accounts and Users
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package accounts_and_users
// IdentityTestIamPermissionsRequest struct for IdentityTestIamPermissionsRequest
type IdentityTestIamPermissionsRequest struct {
	// The set of permissions to test
	Permissions []string `json:"permissions,omitempty"`
}
