/*
 * Edge Compute
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute
// StackpathRpcRetryInfo struct for StackpathRpcRetryInfo
type StackpathRpcRetryInfo struct {
	Type string `json:"@type"`
	RetryDelay string `json:"retryDelay,omitempty"`
}
