/*
 * Edge Compute
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute
// V1VirtualMachineStatus The status of a Virtual Machine
type V1VirtualMachineStatus struct {
	// The name of the virtual machine the status applies to
	Name string `json:"name,omitempty"`
	Phase VirtualMachineStatusPhase `json:"phase,omitempty"`
	// A short reason why the virtual machine is in its current phase
	Reason string `json:"reason,omitempty"`
	// A longer message with details about why the virtual machine is in its current phase
	Message string `json:"message,omitempty"`
}
