/*
 * Edge Compute
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute
// Workloadv1InstanceInstancePhase An instance's startup state  - INSTANCE_PHASE_UNSPECIFIED: StackPath is unable to determine the instance's startup state  - STARTING: The instance is still initializing  - RUNNING: The instance is running  - FAILED: The instance failed to start  - COMPLETED: The instance finished running  - SCHEDULING: The instance is being scheduled  - STOPPED: The instance is stopped
type Workloadv1InstanceInstancePhase string

// List of workloadv1InstanceInstancePhase
const (
	INSTANCE_PHASE_UNSPECIFIED Workloadv1InstanceInstancePhase = "INSTANCE_PHASE_UNSPECIFIED"
	STARTING Workloadv1InstanceInstancePhase = "STARTING"
	RUNNING Workloadv1InstanceInstancePhase = "RUNNING"
	FAILED Workloadv1InstanceInstancePhase = "FAILED"
	COMPLETED Workloadv1InstanceInstancePhase = "COMPLETED"
	SCHEDULING Workloadv1InstanceInstancePhase = "SCHEDULING"
	STOPPED Workloadv1InstanceInstancePhase = "STOPPED"
)
