/*
 * Edge Compute
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute
// Workloadv1NetworkInterfaceStatus Network interfaces that are attached to an instance in a workload
type Workloadv1NetworkInterfaceStatus struct {
	// A network interface's name
	Network string `json:"network,omitempty"`
	// A network interface's primary IP address
	IpAddress string `json:"ipAddress,omitempty"`
	// Additional IP addresses bound to a network interface
	IpAddressAliases []string `json:"ipAddressAliases,omitempty"`
	// A network interface's gateway address
	Gateway string `json:"gateway,omitempty"`
}
