/*
 * Edge Compute
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute
// V1ResourceRequirements Resource requirements for an object  Resource requirements are key/value pairs.
type V1ResourceRequirements struct {
	// A string to string key/value pair
	Requests map[string]string `json:"requests,omitempty"`
	// A string to string key/value pair
	Limits map[string]string `json:"limits,omitempty"`
}
