/*
 * Edge Compute
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute
// V1ImageConditionStatus Which status an image is currently in  - IMAGE_CONDITION_STATUS_UNKNOWN: The condition status is unknown  - TRUE: The condition is true  - FALSE: The condition is false
type V1ImageConditionStatus string

// List of v1ImageConditionStatus
const (
	V1IMAGECONDITIONSTATUS_IMAGE_CONDITION_STATUS_UNKNOWN V1ImageConditionStatus = "IMAGE_CONDITION_STATUS_UNKNOWN"
	V1IMAGECONDITIONSTATUS_TRUE V1ImageConditionStatus = "TRUE"
	V1IMAGECONDITIONSTATUS_FALSE V1ImageConditionStatus = "FALSE"
)
