/*
 * Edge Compute
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package edge_compute

import (
	"encoding/json"
)

// V1GetLocationsResponse A response from a request to retrieve the locations a workload may be created at
type V1GetLocationsResponse struct {
	PageInfo *PaginationPageInfo `json:"pageInfo,omitempty"`
	// The requested locations
	Results *[]Workloadv1Location `json:"results,omitempty"`
}

// NewV1GetLocationsResponse instantiates a new V1GetLocationsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV1GetLocationsResponse() *V1GetLocationsResponse {
	this := V1GetLocationsResponse{}
	return &this
}

// NewV1GetLocationsResponseWithDefaults instantiates a new V1GetLocationsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV1GetLocationsResponseWithDefaults() *V1GetLocationsResponse {
	this := V1GetLocationsResponse{}
	return &this
}

// GetPageInfo returns the PageInfo field value if set, zero value otherwise.
func (o *V1GetLocationsResponse) GetPageInfo() PaginationPageInfo {
	if o == nil || o.PageInfo == nil {
		var ret PaginationPageInfo
		return ret
	}
	return *o.PageInfo
}

// GetPageInfoOk returns a tuple with the PageInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GetLocationsResponse) GetPageInfoOk() (*PaginationPageInfo, bool) {
	if o == nil || o.PageInfo == nil {
		return nil, false
	}
	return o.PageInfo, true
}

// HasPageInfo returns a boolean if a field has been set.
func (o *V1GetLocationsResponse) HasPageInfo() bool {
	if o != nil && o.PageInfo != nil {
		return true
	}

	return false
}

// SetPageInfo gets a reference to the given PaginationPageInfo and assigns it to the PageInfo field.
func (o *V1GetLocationsResponse) SetPageInfo(v PaginationPageInfo) {
	o.PageInfo = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *V1GetLocationsResponse) GetResults() []Workloadv1Location {
	if o == nil || o.Results == nil {
		var ret []Workloadv1Location
		return ret
	}
	return *o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V1GetLocationsResponse) GetResultsOk() (*[]Workloadv1Location, bool) {
	if o == nil || o.Results == nil {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *V1GetLocationsResponse) HasResults() bool {
	if o != nil && o.Results != nil {
		return true
	}

	return false
}

// SetResults gets a reference to the given []Workloadv1Location and assigns it to the Results field.
func (o *V1GetLocationsResponse) SetResults(v []Workloadv1Location) {
	o.Results = &v
}

func (o V1GetLocationsResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.PageInfo != nil {
		toSerialize["pageInfo"] = o.PageInfo
	}
	if o.Results != nil {
		toSerialize["results"] = o.Results
	}
	return json.Marshal(toSerialize)
}

type NullableV1GetLocationsResponse struct {
	value *V1GetLocationsResponse
	isSet bool
}

func (v NullableV1GetLocationsResponse) Get() *V1GetLocationsResponse {
	return v.value
}

func (v *NullableV1GetLocationsResponse) Set(val *V1GetLocationsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableV1GetLocationsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableV1GetLocationsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV1GetLocationsResponse(val *V1GetLocationsResponse) *NullableV1GetLocationsResponse {
	return &NullableV1GetLocationsResponse{value: val, isSet: true}
}

func (v NullableV1GetLocationsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV1GetLocationsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
